
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"Vinson-HelpRequest-db","number":59,"title":"Vinson - Help Request Database","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/59"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller-GET","number":58,"title":"jc - ucsb organization controller get","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/58"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller","number":56,"title":"jc -  ucsb organization controller and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/56"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Articles-DELETE","number":55,"title":"Harold articles delete","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/55"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Articles-PUT","number":54,"title":"Harold articles put","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/54"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Articles-GET-SHOW","number":48,"title":"Harold articles get show","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/48"},{"author":{"id":"MDQ6VXNlcjcyODkzMDg0","is_bot":false,"login":"haroldmo","name":""},"headRefName":"Harold-Articles-GET-POST","number":47,"title":"Harold articles get post","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/47"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-create-db","number":46,"title":"jc - Created entity and repository class for UCSB Organization.","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/46"},{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-DiningCommsMenuItem-create-db","number":45,"title":"Created database for UCSBDiningCommonsMenuItem","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/45"}]
