
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc3NjU4OTQ3","is_bot":false,"login":"AngelG261","name":""},"headRefName":"Angel-DiningCommsMenuItem-Controller","number":67,"title":"Added controller for UCSBDiningCommonsMenuItems and passed tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/67"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"Vinson-HelpRequest-GET","number":66,"title":"Vinson - Help Request GET (show) controller and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/66"}]
