
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecommendationLetters-delete","number":80,"title":"Implemented Delete Functionality for Recommendation Requests Controller","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/80"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecommendationLetters-PUT","number":79,"title":"Implemented Recommendation Request PUT functionality","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/79"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecommendationLetters-getSingle","number":78,"title":"Recommendation Letters get Single Request Functionality","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/78"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"yv-RecommendationLetters-getAll-post","number":77,"title":"Recommendation Letters get all and POST implemented","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/77"}]
