
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f23/team02-f23-5pm-1
owner: ucsb-cs156-f23
repo_name: team02-f23-5pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller-DELETE","number":63,"title":"- jc ucsb organization controller delete","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/63"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller-PUT","number":62,"title":"jc -  ucsb organization controller put","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/62"},{"author":{"id":"MDQ6VXNlcjU1NTU2Mjk2","is_bot":false,"login":"Yashasvi-Vangala","name":"Yashasvi Vangala"},"headRefName":"Yash-RecommendationLetters-create-db","number":61,"title":"added Entity class and Repository class for RecommendationRequest ","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/61"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"Vinson-HelpRequest-Controller","number":60,"title":"Vinson help request controller (get, post) + tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/60"},{"author":{"id":"MDQ6VXNlcjg3MDUzNTg3","is_bot":false,"login":"vinsonlinn","name":""},"headRefName":"Vinson-HelpRequest-db","number":59,"title":"Vinson - Help Request Database","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/59"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller-GET","number":58,"title":"jc - ucsb organization controller get","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/58"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-Controller","number":56,"title":"jc -  ucsb organization controller and tests","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/56"},{"author":{"id":"MDQ6VXNlcjc1ODIzOTg5","is_bot":false,"login":"pingyujc","name":""},"headRefName":"Jonathan-UCSBOrganization-create-db","number":46,"title":"jc - Created entity and repository class for UCSB Organization.","url":"https://github.com/ucsb-cs156-f23/team02-f23-5pm-1/pull/46"}]
